export enum Navigations {
  Onboarding = "Onboarding",
  Auth = "Auth",
  Auth_Signin = "Auth_Signin",
  Auth_Signup = "Auth_Signup",
  Main = "Main",
  Main_BottomBar = "Main_BottomBar",
  BottomBar_Home_Stack = "BottomBar_Home_Stack",
  Home_Stack_Home = "Home_Stack_Home",
  Home_Stack_Search = "Home_Stack_Search",
  Home_Stack_Filter = "Home_Stack_Filter",
  Home_Stack_SearchResult = "Home_Stack_SearchResult",
  BottomBar_Favorites = "BottomBar_Favorites",
  BottomBar_ShoppingList = "BottomBar_ShoppingList",
  BottomBar_Account = "BottomBar_Account",
  Account_Profile = "Account_Profile",
  Account_Settings = "Account_Settings",
  Main_Rating = "Main_Rating",
  Main_VideoClip = "Main_VideoClip",
}
